server:
  port: 9001
  context-path: /${spring.application.name}

spring:
  application:
    name: 'zuul'

zuul:
  routes:
    google:
      url: https://www.google.be
    rest:
      path: /rest/**
      serviceId: rest
      retryable: true

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eurekaserver/eureka/