server:
  port: 8080
  context-path: /${spring.application.name}

spring:
  application:
    name: rest

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eurekaserver/eureka/